/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 girl1.gltf 
Author: 腱鞘炎の人 (https://sketchfab.com/Kensyouen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/just-a-girl-b2359160a4f54e76b5ae427a55d9594d
Title: Just a girl
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model1(props) {
  const { nodes, materials } = useGLTF('/girl1.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 200]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.lambert5SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.lambert5SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.lambert5SG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.lambert7SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/girl1.gltf')
